version: 0.4.1.{build}
image: Visual Studio 2017
environment:
  SWITCH_BUILD_WIN32: false
  SWITCH_BUILD_WIN64: true

build_script: scripts\appveyor\build_script.bat %SWITCH_BUILD_WIN32% %SWITCH_BUILD_WIN64%
test_script: scripts\appveyor\test_script.bat %SWITCH_BUILD_WIN32% %SWITCH_BUILD_WIN64%
on_success: scripts\appveyor\on_success.bat %SWITCH_BUILD_WIN32% %SWITCH_BUILD_WIN64%
