os:
  - linux
  - osx

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - clang++-3.7
      - g++-5
      - gcc-5
            
osx_image: xcode8.3
dist: trusty
sudo: enabled
compiler: clang
language: cpp

script:
  - cmake --version
  - mkdir -p Build/Examples
  - mkdir -p Build/ThirdParties
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install clang cmake doxygen libcurlpp-dev libgtkmm-3.0-dev libjpeg8-dev libpng-dev libssl-dev libx11-dev uuid-dev zlibc -y; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main' | sudo tee -a /etc/apt/sources.list; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install clang-3.8 lldb-3.8 cmake doxygen libcurlpp-dev libgtkmm-3.0-dev libjpeg8-dev libpng-dev libssl-dev libx11-dev uuid-dev zlibc -y; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=clang-3.8; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=clang++-3.8; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake curl doxygen fltk gtkmm3 jpeg libpng zlib -y; fi
  - cd Build/ThirdParties
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../../ThirdParties 
  - make all -j6
  - sudo make install
  - cd ..
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_CORE_UNIT_TESTS=ON -DBUILD_DRAWING_UNIT_TESTS=ON -DBUILD_FORMS_UNIT_TESTS=ON -DBUILD_TUNIT_UNIT_TESTS=ON ..
  - make all -j6
