# configuration
language: cpp
dist: trusty
sudo: require

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-3.9
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - clang-3.9
      - doxygen
      - lldb-3.9
      - libgtkmm-3.0-dev
      - uuid-dev

# build matrix
matrix:
  include:
  
    # build Switch on macOS
    - os: osx
      cache: ccache
      osx_image: xcode9.1
      before_script: scripts/travis/build_3rdparty.sh
      script: scripts/travis/build.sh
      after_success: scripts/travis/coverage.sh

    # build Switch on linux`
    #- os: linux
    #  cache: ccache
    #  compiler: clang-3.9
    #  before_script: scripts/travis/build_3rdparty.sh
    #  script: scripts/travis/build.sh
    #  after_success: scripts/travis/after_success.sh

    # generate Reference Guide
    - os: linux
      compiler: clang-3.9
      before_script: scripts/travis/build_3rdparty.sh
      script: scripts/travis/generate_reference_guide.sh
      