language: cpp
os: osx
osx_image: xcode9.1
cache: ccache
script: "./scripts/travis/script.sh"
after_success: "./scripts/travis/after_success.sh"
env:
  global:
    secure: GElPsvm52XhOLps6y+q3icvhYZDPLE7U8SJPpFvWDnTPKm7luj4EaHyMHIjG8pNP9HUstt/3IvXL7uoghVupPFi5BO9EDfyDpsDqVQqPQCla3FxM0iOdrw3Qmw3b0LKQ/fTBoUpcX4iedt/YlJVRy5+6h0WnW4il64y9MQhjAy/a7UM86XtF/phROq6wvs3uFvWCc3Lx49kE6T9XvD/TQVBgvDHSs5kawb55hAwZt8cp6cGvGrQQydJKLi9gg9ZP+9ts79emQjjSonJCkFGK9USqyek3i7xrPmjMFOMCB2M0Uh0ChXjVT3iegPvJhNWM3IEICmvqSrSVNGdXzvX5Oo24hd7jxXZNahiil4m9OYo4JaIzHodbvmM7q98rZVS0S1VjXQ6nUOAe2Z0hr4EXe2Qi3PTycsUeYLtb8frilPqsvqjTXoy+CSVAkAzHXYKZILap/YRreTNhR3I8sJEPhMrzy9mWHvQkQ+xSA0hYi6BnGUZ+NGpruvNkFp1cAxE244Cvj8QCBfadbUTTOYatg+TxKl2auIXCA92WwF0vpee/cn8Vb9ny6YtvnticX/V6h79aO9DrFrO1RCah4Czq/ZjARCPeS+56oi1/YFDeUR76/sp9vUIQRqXW8vN/3wkNKsuKr5E/gkWp9L7D/usOUCGXksNmCHfNNt0ubEsh7wM=
