language: cpp
cache: ccache

matrix:
  include:
    #- os: linux
    #  compiler: clang
    #  sudo: require
    #  dist: trusty
    - os: osx
      compiler: clang
      osx_image: xcode8.3

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test

before_install: source ./scripts/travis/before_install.sh
install: source ./scripts/travis/install.sh
before_script: source ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
after_success: ./scripts/travis/after_success.sh
