language: cpp
#cache: ccache

matrix:
  include:
    #- os: linux
    #  compiler: clang-3.9
    #  sudo: require
    #  dist: trusty
    - os: osx
      compiler: clang
      osx_image: xcode9.1

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-3.9
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - clang-3.9
      - lldb-3.9
      - libcurlpp-dev
      - libgtkmm-3.0-dev
      - libjpeg8-dev
      - libssl-dev
      - libx11-dev
      - uuid-dev
      - zlibc

before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
after_success: ./scripts/travis/after_success.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl jpeg libpng zlib -y; fi
  - mkdir -p build/3rdparty
  - cd build/3rdparty
  - cmake -DCMAKE_BUILD_TYPE=Release ../../3rdparty 
  - cmake --build . -- -j8
  - sudo cmake --build . --target install -- -j8
  - cd ..
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
  - cmake --build . -- -j8
  - ctest --output-on-failure --build-config Release
