# configuration
language: cpp
dist: trusty
env:
  global:
    - secure: GElPsvm52XhOLps6y+q3icvhYZDPLE7U8SJPpFvWDnTPKm7luj4EaHyMHIjG8pNP9HUstt/3IvXL7uoghVupPFi5BO9EDfyDpsDqVQqPQCla3FxM0iOdrw3Qmw3b0LKQ/fTBoUpcX4iedt/YlJVRy5+6h0WnW4il64y9MQhjAy/a7UM86XtF/phROq6wvs3uFvWCc3Lx49kE6T9XvD/TQVBgvDHSs5kawb55hAwZt8cp6cGvGrQQydJKLi9gg9ZP+9ts79emQjjSonJCkFGK9USqyek3i7xrPmjMFOMCB2M0Uh0ChXjVT3iegPvJhNWM3IEICmvqSrSVNGdXzvX5Oo24hd7jxXZNahiil4m9OYo4JaIzHodbvmM7q98rZVS0S1VjXQ6nUOAe2Z0hr4EXe2Qi3PTycsUeYLtb8frilPqsvqjTXoy+CSVAkAzHXYKZILap/YRreTNhR3I8sJEPhMrzy9mWHvQkQ+xSA0hYi6BnGUZ+NGpruvNkFp1cAxE244Cvj8QCBfadbUTTOYatg+TxKl2auIXCA92WwF0vpee/cn8Vb9ny6YtvnticX/V6h79aO9DrFrO1RCah4Czq/ZjARCPeS+56oi1/YFDeUR76/sp9vUIQRqXW8vN/3wkNKsuKr5E/gkWp9L7D/usOUCGXksNmCHfNNt0ubEsh7wM=

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-3.9
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - clang-3.9
      - doxygen
      - lldb-3.9
      - libgtkmm-3.0-dev
      - uuid-dev

# build matrix
matrix:
  include:
  
    # build Switch on macOS
    - os: osx
      env: TEST="Switch build"
      cache: ccache
      osx_image: xcode9.1
      before_script: scripts/travis/build_3rdparty.sh
      script: scripts/travis/build.sh
      after_success: scripts/travis/coverage.sh

    # build Switch on linux`
    #- os: linux
    #  env: TEST="Switch build"
    #  cache: ccache
    #  compiler: clang-3.9
    #  before_script: scripts/travis/build_3rdparty.sh
    #  script: scripts/travis/build.sh
    #  after_success: scripts/travis/after_success.sh

    # generate Reference Guide
    - os: linux
      env: TEST="Reference Guide generation"
      compiler: clang-3.9
      before_script: scripts/travis/build_3rdparty.sh
      script: scripts/travis/generate_reference_guide.sh
